# ビルドステージ
FROM mcr.microsoft.com/dotnet/sdk:3.1-nanoserver-1809 AS builder

WORKDIR /Worker
COPY Worker/Worker.csproj .
RUN dotnet restore

COPY /Worker .
RUN dotnet publish -c Release -o /out Worker.csproj

# アプリイメージ
FROM mcr.microsoft.com/dotnet/aspnet:3.1-nanoserver-1809

WORKDIR /app
ENTRYPOINT ["dotnet", "Worker.dll"]

COPY --from=builder /out .
